# @WebAPI_HostAddress = https://localhost:7093

GET {{HostAddress}}/api/album/
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImxpbmtzIiwic3ViIjoibGlua3MiLCJqdGkiOiIzODc0YTc2NSIsInNjb3BlIjoid2ViLWFwaTpyZWFkIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTI4MyIsImh0dHBzOi8vbG9jYWxob3N0OjcwOTMiXSwibmJmIjoxNzQzNzg4MjIyLCJleHAiOjE3NDM3OTE4MjIsImlhdCI6MTc0Mzc4ODIyMywiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.e8bJY88HivujTd26Nm0J3bN98bNC7nyDNVOu4MCv-aE
Accept: application/json
x-api-version: 1.0

###

# With web-api:read scope
GET {{HostAddress}}/api/album/5
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImxpbmtzIiwic3ViIjoibGlua3MiLCJqdGkiOiIzODc0YTc2NSIsInNjb3BlIjoid2ViLWFwaTpyZWFkIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTI4MyIsImh0dHBzOi8vbG9jYWxob3N0OjcwOTMiXSwibmJmIjoxNzQzNzg4MjIyLCJleHAiOjE3NDM3OTE4MjIsImlhdCI6MTc0Mzc4ODIyMywiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.e8bJY88HivujTd26Nm0J3bN98bNC7nyDNVOu4MCv-aE
Accept: application/json
x-api-version: 1.0

###

# With web-api:admin scope
GET {{HostAddress}}/api/album/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImxpbmtzIiwic3ViIjoibGlua3MiLCJqdGkiOiJhNDEyNTRhYyIsInNjb3BlIjoid2ViLWFwaTphZG1pbiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUyODMiLCJodHRwczovL2xvY2FsaG9zdDo3MDkzIl0sIm5iZiI6MTc0Mzc4ODMxMCwiZXhwIjoxNzQzNzkxOTEwLCJpYXQiOjE3NDM3ODgzMTEsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.Eo0roumFgVznGbxmyMq54j5xL1rE3chSPuuXUrvLOcs
Accept: application/json
x-api-version: 1.0

###

# Successful when no tracks exist for the album
DELETE {{HostAddress}}/api/album/348
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImxpbmtzIiwic3ViIjoibGlua3MiLCJqdGkiOiJhNDEyNTRhYyIsInNjb3BlIjoid2ViLWFwaTphZG1pbiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUyODMiLCJodHRwczovL2xvY2FsaG9zdDo3MDkzIl0sIm5iZiI6MTc0Mzc4ODMxMCwiZXhwIjoxNzQzNzkxOTEwLCJpYXQiOjE3NDM3ODgzMTEsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.Eo0roumFgVznGbxmyMq54j5xL1rE3chSPuuXUrvLOcs
Accept: application/json
x-api-version: 1.0
